#!/bin/bash

# downloads NED data for the specified region

if [[ -z $TOPOSM_ENV_SET ]]; then
echo "Error: TopOSM environment not set."
    exit 1
fi

# TODO: fix zero-prefixed west coordinates

W=$(($XMINLL * -1))
N=$YMAXLL
E=$(($XMAXLL * -1))
S=$YMINLL

pushd $NED13_DIR

echo "Downloading NED data for BBOX($S $W, $N $E)"
SRC="http://tdds.cr.usgs.gov/ned/13arcsec/float/float_zips"
for n in `seq $S $N` ; do
    for w in `seq $E $W`; do
        NAME=n${n}w${w}
        if [ -d $NAME \
            -o -s $NAME.zip \
            -o -s $NAME.flt ]; then
           echo "$NAME appears to exist already...skipping"
        else
            wget "$SRC/$NAME.zip"
            unzip $NAME.zip
            if [ -s $NAME/float${NAME}_13 ]; then
                mv $NAME/float${NAME}_13 $NAME.flt
            fi
            rename "s/$NAME\/float${NAME}_13/$NAME/" $NAME/float${NAME}_13.*
            rm -rf $NAME
        fi
    done
done

popd
